version: "3.9"
services:
  backend:
    build:
      context: ./mobile-troubleshooter-backend
    env_file:
      - ./mobile-troubleshooter-backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    # Uncomment to mount source during local dev
    # volumes:
    #   - ./mobile-troubleshooter-backend:/app